import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const harabara = localFont({
  src: "./fonts/Harabara.woff",
  variable: "--font-harabara",
  weight: "100 700 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const urbanist = Urbanist({
  subsets: ["latin"], // Include subsets as needed
  weight: ["700"], // Include only the weights you need
  variable: "--font-urbanist", // Define a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${harabara.variable} ${urbanist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
